routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if(auth()->check()){
        return view('pages.index');
    }else{
    return redirect()->route('login');
    }
});
Route::middleware(['auth'])->group(function () {    Route::get('dashboard', function () {return view('pages.index');})->name('dashboard');
    Route::get('guide', function () {return view('guide');})->name('guide');
    Route::get('settings', function () {
        $user = auth()->user();
        return view('settings',compact('user'));
    })->name('settings');
    Route::resources([
        'locations' => 'LocationController',
        'ads' => 'adsCtrl',
        //'marketingBenefactors' => 'MarketingBenefactorCtrl',
        //'callBenefactors' => 'callBenefactorsCtrl',
        'permissions' => 'permissionsCtrl',
        'roles' => 'rolesCtrl',
        //'assignmentsToCallEmps' => 'AssignToCallEmpCtrl',
        //'call_assignments' => 'callCenterAssignmentsCtrl',
        //'collect_assignments' => 'collectAssignmentsCtrl',
       // 'calls' => 'CallController',
    ]);
    //Route::post('marketing/benefactor/{newBenefactor}/send','MarketingBenefactorCtrl@send')->name('marketing.benefactor.send');
    Route::prefix('users')->group(static function () {
        Route::get('all','adminCtrl@users')->name('users.all');
        Route::post('roles/update/{user}','adminCtrl@updateRoles')->name('users.roles.update');
        Route::post('permissions/update/{user}','adminCtrl@updatePermissions')->name('users.permissions.update');

    });

    Route::prefix('notifications')->group(static function () {
        Route::post('/markAsRead','notficationCtrl@markAsRead')->name('readNotification');
    });

//    Route::get('/benefactors/dataFile/{id}/{assignment?}','benefactorCtrl@dataFile' )->name('benefactor.data.file');
//
//    Route::prefix('calls')->group(static function () {
//        //Route::get('{assignment?}/benefactor/{id}','callBenefactorsCtrl@show')->name('assignment.Benefactors.show');
//       // Route::Post('{assignment}/benefactor/{id}','callBenefactorsCtrl@store')->name('assignment.Benefactors.store');
////        Route::Post('{assignment}/collect','CollectRequestsController@store')->name('assignment.collectRequest.store');
////        Route::Put('{collectRequests}/update','CollectRequestsController@update')->name('assignment.collectRequest.update');
//
//    });

//    Route::get('assignments-old','callCenterAssignmentsCtrl@old')->name('old_assignments.callCenter');
//
//    Route::prefix('callcenter_manager')->group(static function () {
//        Route::get('/benefactors/new', 'CallManagerCtrl@newBenefactors')->name('callManager.new.benefactors');
//        Route::post('/newBenefactors/{benefactor}/assignToCallemp', 'CallManagerCtrl@assignTocallemp')->name('callManager.newBenefactors.assignTocallemp');
//        Route::get('/benefactors/actual', 'CallManagerCtrl@actualBenefactors')->name('actualBenefactors');
//        Route::get('/benefactors/kafalah', 'CallManagerCtrl@kafalah')->name('all.kafalah');
//        Route::get('/benefactors/stopped', 'CallManagerCtrl@AllStopped')->name('all.stopped');
//        Route::get('/benefactors/forCollect', 'CallManagerCtrl@forCollectBenefactors')->name('callManager.benefactors.forCollect');
//        Route::get('/assignments/team', 'CallManagerCtrl@team')->name('callManager.assignments.team');
//        Route::get('/assignments/emp/{emp}', 'CallManagerCtrl@emp')->name('callManager.assignments.temp');
//        Route::get('/EmpAssignment/{id}', 'CallManagerCtrl@empAssignment')->name('call.emp.assignment');
//        Route::get('/excelfile', 'ExcelCtrl@uploadFile')->name('callManager.uploadFile');
//        Route::post('/excelfile', 'ExcelCtrl@storeFile')->name('callManager.storeFile');
//
//        Route::post('/EditRequestRefuse/{id}', 'CallManagerCtrl@refuseEditRequest')->name('callManager.editRequest.refuse');
//        Route::post('/EditRequestAccept/{id}', 'CallManagerCtrl@acceptEditRequest')->name('callManager.editRequest.accept');
//
//        Route::get('/readyAssignment/forcollect','CallManagerCtrl@forCollectAssignments')->name('callManager.forCollect.assignments');
//        Route::post('/sendAssignment/forcollect/{assignment}','CallManagerCtrl@sendAssignmentforCollectManager')->name('send.assignment.to.collectManager');
//
//    });
//
//    Route::post('benefactors/{benefactor}/stopAllHisActivities', 'benefactorCtrl@stopAllHisActivities')->name('stopAllHisActivities');
//    Route::post('benefactors/{benefactor}/restore', 'benefactorCtrl@restore')->name('benefactor.restore');
//    Route::post('collectAssignments/{collection}/collected','collectAssignmentsCtrl@collectedDone')->name('collect.action.done');
//    Route::post('collectAssignments/{collection}/failed','collectAssignmentsCtrl@failedCollect')->name('collect.action.fail');
//    Route::post('collectAssignments/{collection}/changeEmp','collectAssignmentsCtrl@changeEmpForCollect')->name('changeEmpForCollect');
//    Route::post('collectAssignments/{assignment}/markAsfailed','collectAssignmentsCtrl@markAsfailed')->name('markAsfailed');
//    Route::get('newCollectAssignments','collectAssignmentsCtrl@nowatime')->name('collectAssignments.myNew');
//    Route::get('oldCollectAssignments','collectAssignmentsCtrl@old')->name('collectAssignments.old');
//    Route::get('failedCollectAssignments','collectAssignmentsCtrl@allFailds')->name('collectAssignments.faild');
//    Route::get('doneCollectAssignments','collectAssignmentsCtrl@done')->name('collectAssignments.done');
//    Route::get('immediateCollectAssignments','collectAssignmentsCtrl@immediate')->name('collectAssignments.immediate');
//
//    Route::prefix('reports')->group(static function () {
//    #reports
//        Route::view('/ad/report', 'reports.singlAd')->name('ad.report');
//        Route::view('/ads_benefactors/report', 'reports.allAds')->name('ads_benefactors.report');
//        Route::view('/ads_costs/report', 'reports.allAdsCosts')->name('ads_costs.report');
//    #Reports
//        Route::view('/all_benefactors/report', 'reports.allBenefactors')->name('all_benefactors.report');
//        Route::view('/all_kafalah/report', 'reports.allKafalah')->name('all_kafalah.report');
//        Route::view('/all_Aini/report', 'reports.allAini')->name('all_aini.report');
//
//    });
//
//    Route::prefix('account_manager')->group(static function () {
//        Route::get('/ToConfirmCall/collects','accountManagerCtrl@toCall')->name('toCollectConfirmCall');
//        Route::get('/assignments/delayed','accountManagerCtrl@delayed')->name('toCollectDelayedCalls');
//        Route::get('/assignments/failed','accountManagerCtrl@faild')->name('toCollectFaildCalls');
//        Route::get('/assignments/confirmed','accountManagerCtrl@confirmed')->name('toCollectconfirmedCalls');
//        Route::get('/team','accountManagerCtrl@team')->name('account.team');
//        Route::get('/team/{emp}','accountManagerCtrl@emp')->name('account.emp');
//
//        //calls results:
//        Route::post('/assignments/{assignment}/confirm','accountManagerCtrl@confirm')->name('Confirm.Call');
//        Route::post('/assignments/{assignment}/delay','accountManagerCtrl@delay')->name('delay.Call');
//        Route::post('/assignments/{assignment}/reject','accountManagerCtrl@reject')->name('reject.Call');
//        Route::post('/assignments/{assignment}/assignToCollect','accountManagerCtrl@assignToCollect')->name('assignToCollect');
//    });
//
//    Route::prefix('manager')->group(static function () {
//        Route::view('/benefactors', 'pages.manager.allBenefactors')->name('manager.benefactors');
//        Route::view('/benefactors/single', 'pages.manager.benefactor')->name('manager.benefactor');
//        Route::view('/kafalat', 'pages.manager.allKafalat')->name('manager.allKafalat');
//        Route::view('/kafalat/single', 'pages.manager.kafalah')->name('manager.kafalah');
//        Route::view('/emps', 'pages.manager.allEmps')->name('manager.emps');
//        Route::view('/emps/single', 'pages.manager.emp')->name('manager.emp');
//        Route::view('/ads', 'pages.manager.allAds')->name('manager.ads');
//        Route::view('/ads/single', 'pages.manager.ad')->name('manager.ad');
//        Route::view('/ads/costs', 'pages.manager.adsCosts')->name('manager.ads.cost');
//        Route::view('/ads/locations', 'pages.manager.locations')->name('manager.locations');
//        Route::view('/aini', 'pages.manager.aini')->name('manager.aini');
//        Route::view('/mony', 'pages.manager.mony')->name('manager.mony');
//        Route::view('/callManager', 'pages.manager.blank')->name('manager.callManager');
//        Route::view('/marketingManager', 'pages.manager.blank')->name('manager.marketingManager');
//        Route::view('/accountManager', 'pages.manager.blank')->name('manager.accountManager');
//
//
//    });
});
Auth::routes();

Route::get('/home', function () {

        return redirect()->route('login');

})->name('home');

app/newBenefactor.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class newBenefactor extends Model
{
    use SoftDeletes;
    protected $guarded = [''];


    // scopes:


    public function scopeNew($query)
    {
        return $query->where('sent',0)->where('assigned',0)->where('moved',0)->where('end',0);
    }
    public function scopeSent($query)
    {
        return $query->where('sent',1)->where('assigned',0)->where('moved',0)->where('end',0);
    }
    public function scopeAssigned($query)
    {
        return $query->where('sent',1)->where('assigned',1)->where('failed',0)->where('moved',0)->where('end',0);
    }
    public function scopeFailed($query)
    {
        return $query->where('sent',1)->where('assigned',1)->where('failed',1)->where('moved',0)->where('end',0);
    }
    public function scopeMoved($query) //moved To Benefactor Table
    {
        return $query->where('sent',1)->where('assigned',1)->where('failed',0)->where('moved',1)->where('end',0);
    }
    public function scopeNotMoved($query) //moved To Benefactor Table
    {
        return $query->where('sent',1)->where('assigned',1)->where('failed',0)->where('notMoved',1)->where('end',0);
    }
    public function scopeEnd($query) // sent To Collections center
    {
        return $query->where('end',1);
    }





    // relations :

    public function adable()
    {
        return $this->morphTo();
    }

    public function assignment()
    {
        return $this->morphOne(Assignment::class ,'benefactorable');
    }
    public function actualBenefactor()
    {
        return $this->morphOne(Benefactor::class ,'benefactorable');
    }
    public function calls()
    {
        return $this->morphMany(Call::class ,'benefactorable');
    }



    // git attribute
    public function getStatusAttribute()
    {
        if($this->sent == 0) return 'جديد';
        if($this->sent == 1 && $this->assigned == 0) return 'جديد';
        if($this->sent == 1 && $this->assigned == 1 && $this->failed == 0 && $this->moved == 0) return 'جاري التواصل';
        if($this->sent == 1 && $this->assigned == 1 && $this->failed == 1 && $this->moved == 0) return 'فشل التواصل';
        if($this->sent == 1 && $this->assigned == 1 && $this->moved == 1) return 'متبرع فعلي';
    }
    public function getIsNewAttribute()
    {
        if($this->sent == 0) return true;
        return false;
    }
    public function getIsSentAttribute()
    {
        if($this->sent == 1 && $this->assigned == 0) return true;
        return false;
    }
    public function getIsAssignedAttribute()
    {
        if($this->sent == 1 && $this->assigned == 1 && $this->moved == 0) return true;
        return false;
    }
    public function getIsFaildAttribute()
    {
        if($this->sent == 1 && $this->assigned == 1 && $this->moved == 0) return true;
        return false;
    }
    public function getIsMovedAttribute()
    {
        if($this->sent == 1 && $this->assigned == 1 && $this->moved == 1) return true;
        return false;
    }

}

app/Http/Controllers/teams/callTeamCtrl.php
<?php

namespace App\Http\Controllers\teams;

use App\Assignment;
use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Http\Request;

class callTeamCtrl extends Controller
{
    public function index()
    {

        $emps = User::whereRoleIs('call_emp')->orWhereRoleIs('call_manager')->get();
        return view('pages.callCenter.team.index',compact('emps'));

    }

    public function show(User $emp)
    {
        $assignments = $emp->employeeAssignments()->orderBy('id','DESC')->get();
        return view('pages.callCenter.team.show',compact('emp','assignments'));
    }
    public function assignment( Assignment $assignment)
    {
        return view('pages.callCenter.team.assignment',compact('assignment'));
    }
}

app/Http/Controllers/teams/collectTeamCtrl.php
<?php

namespace App\Http\Controllers\teams;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class collectTeamCtrl extends Controller
{
    public function addAccountant()
    {
        return view('pages.users.addUser');
    }
    public function storeAccountant(Request $request)
    {
        $request->validate([
           'name'=>'required|string' ,
           'email'=>'required|email|unique:users',
           'phone'=>'required|string'
        ]);
    }

}

resources/views/pages/callCenter/team/index.blade.php
@extends('pages.layouts.app')
@section('content')

<!-- Begin Page Content -->
<div class="container-fluid  ">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb bg-white">
            <li class="breadcrumb-item"><a href="{{route('dashboard')}}">لوحة التحكم</a></li>
            <li class="breadcrumb-item active" aria-current="page">فريق الكول سنتر</li>
        </ol>
    </nav>

    @component('components.table',['color'=>'primary','title'=>'فريق الكول سنتر'])
        <thead>
        <tr>
            <th>#</th>
            <th>الموظف</th>
            <th> عدد العمليات التامة</th>
            <th>عدد العمليات الحالية</th>
            <th>المكالمات</th>
            <th>متابعة</th>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <th>#</th>
            <th>الموظف</th>
            <th> عدد العمليات التامة</th>
            <th>عدد العمليات الحالية</th>
            <th>المكالمات</th>
            <th>متابعة</th>
        </tr>
        </tfoot>
        <tbody>
            @foreach($emps as  $key=>$emp)
            <tr>
                <td>{{$key+1}}</td>
                <td>{{$emp->name}}</td>
                <td> {{$emp->employeeAssignments->where('done',1)->count()}}  </td>
                <td> {{$emp->employeeAssignments->where('done','<>',1)->count()}}  </td>
                <td>{{$emp->calls->count()}} </td>
                <td > <a class="btn btn-warning " href="{{route('callCenter.show',$emp->id)}}"> <i class="fas fa-eye"></i> </a> </td>
            </tr>
            @endforeach
        </tbody>
    @endcomponent
</div>
@stop

resources/views/pages/callCenter/team/show.blade.php
@extends('pages.layouts.app')
@section('css')
<link href="{{asset('assets/vendor/datatables/dataTables.bootstrap4.min.css')}}" rel="stylesheet">
@stop
@section('content')

<!-- Begin Page Content -->
<div class="container-fluid  ">
    <!-- Content Row -->
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb bg-white">
            <li class="breadcrumb-item"><a href="{{route('dashboard')}}">لوحة التحكم</a></li>
            <li class="breadcrumb-item"><a href="{{route('callCenter.team')}}">فريق الكول سنتر</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{$emp->name}}</li>
        </ol>
    </nav>

    <div class="row">

        <!-- Earnings (Monthly) Card Example -->
        <div class="col-xl-4 col-md-6 mb-4">
            <div class="card border-left-warning shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">عدد كافة عمليات التواصل</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800"> {{$emp->employeeAssignments->count()}}</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-calendar fa-2x  text-primary"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Earnings (Monthly) Card Example -->
        <div class="col-xl-4 col-md-6 mb-4">
            <div class="card border-left-warning shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1"> عدد عمليات التواصل الحالية</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800"> {{$emp->employeeAssignments->where('done','<>',1)->count()}}</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-link fa-2x  text-primary"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Earnings (Monthly) Card Example -->
        <div class="col-xl-4 col-md-6 mb-4">
            <div class="card border-left-warning shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">عدد المكالمات</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{$emp->calls->count()}}</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-phone fa-2x  text-primary"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@component('components.table',['color'=>'primary','title'=>'عمليات التواصل'])
        <thead>
        <tr>
            <th>#</th>
            <th>التاريخ</th>
            <th>من خلال</th>
            <th> المتبرع</th>
            <th> الحالة</th>
            <th class="text-center">عرض</th>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <th>#</th>
            <th>التاريخ</th>
            <th>من خلال</th>
            <th> المتبرع</th>
            <th> الحالة</th>
            <th class="text-center">عرض</th>
        </tr>
        </tfoot>
        <tbody>
        @foreach($assignments as $key=>$assignment)
            <tr>
                <td>{{$key+1}}</td>
                <td>{{getDateTime($assignment->created_at)}}</td>
                <td>{{$assignment->assignmentable->name}}</td>
                <td>{{$assignment->benefactorable->name}}</td>
                <td>{{$assignment->status}}</td>
                <td class="text-center"><a class="text-white btn btn-warning" href="{{route('callCenter.emp.assignment',$assignment)}}"> <i class="fa fa-eye"></i> </a></td>
            </tr>


        @endforeach
        </tbody>
@endcomponent
      <!-- Grow In Utility -->


  </div>
  <!-- /.container-fluid -->

@stop
@section('js')
    <!-- Page level plugins -->
    <script src="{{asset('assets/vendor/datatables/jquery.dataTables.min.js')}}"></script>
    <script src="{{asset('assets/vendor/datatables/dataTables.bootstrap4.min.js')}}"></script>

    <!-- Page level custom scripts -->
    <script src="{{asset('assets/js/demo/datatables-demo.js')}}"></script>


@stop